export { default as BannerSection } from "./Banner/banner";
export { default as ProcessSection } from "./Process/process";
export { default as GetInTouch } from "./GetInTouch/getInTouch.jsx";
export { default as PerformanceSection } from "./Performance/performance";
export { default as IndustrySection } from "./Industry/industry.jsx"
export { default as OurProjects } from "./Projects/projects.jsx"
export { default as Qualification } from "./Qualification/qualification.jsx"
export { default as TestimonialSection } from "./Testimonial/testimonialSection.jsx"
export { default as PricingSection } from "./Pricing/pricingSection"
export { default as TeamSection } from "./Team/team.jsx"
