export { default as NewBannerSection } from "./Banner/newbanner";
export { default as ProcessSection } from "./Process/NewProcess";
export { default as NewGetInTouch } from "./GetInTouch/newgetintouch";
export { default as NewPerformanceSection } from "./Performance/newperformance";
export { default as NewIndustrySection } from "./Industry/newindustry.jsx"
export { default as NewOurProjects } from "./Projects/NewProjects.jsx"
export { default as NewQualification } from "./Qualification/NewQualification.jsx"
export { default as NewTestimonialSection } from "./Testimonial/NewTestimonialSection.jsx"
export { default as NewPricingSection } from "./Pricing/NewPricingSection.jsx"
export { default as NewTeamSection } from "./Team/NewTeam.jsx"
